name: 'LabelingWhenApproved'
description: 'If the PR is approximated by a certain number, attach the APPROVEL label'
inputs:
  github-token:  # id of input
    description: 'github token'
    required: true
  approves-number:
    description: 'Number of approves count'
    required: true
  label-name:
    description: 'Label name to specify'
    required: false
    default: 'APPROVE'
 # outputs:
 #   time: # id of output
 #     description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'
